# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: projectname_development
  pool: 5
  username: username
  password: password

test: &TEST
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: projectname_test
  pool: 5
  username: username
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: projectname_production
  pool: 5
  username: username
  password: password